### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by Nihility981** [pritamSankhari/whatsapp-last-seen-tracker#1]
rt

**Comment by pritamSankhari** [comment]
This issue is fixed temporarily. 
[Check out the updated code here](https://github.com/pritamSankhari/whatsapp-last-seen-tracker/blob/master/wls.js)

`lastSeenData = document.querySelector("._7yrSq._3-8er").textContent`
**Since Whatsapp daily updates their web application , it is quite tough to detect and maintain the html span element class daily which shows the online status**
